CREATE TABLE convivio (
id INT NOT NULL,
NOMBRE_TITULAR VARCHAR(100) NOT NULL,
ACOPANANTE1 VARCHAR(100),
ACOPANANTE2 VARCHAR(100),
NINO VARCHAR(100),
EDAD_NINO INT,
REQUERIMIENTO VARCHAR(100),
PROVINCIA VARCHAR(100),
HOTEL VARCHAR(100),
PRIMARY KEY (id)
);